"use strict";

const MAX_COMMAND_LENGTH = 32;
const MAX_ARGS = 32;
const MAX_ARG_LENGTH = 1024;
const MAX_ENV_KEYS = 32;
const MAX_ENV_VALUE_LENGTH = 4096;
const MAX_JSON_INPUT_CHARS = 1_000_000;
const MAX_SYSTEM_PROMPT_CHARS = 200_000;
const MAX_TOOLS = 64;
const MAX_TOOL_LENGTH = 256;
const MAX_PACKAGE_NAME_LENGTH = 214;
const MAX_TEST_PII_LENGTH = 2048;
const MAX_SERVERS_PER_CONFIG = 25;
const ACTIVE_SERVER_PROBING_DISABLED_MESSAGE = "Active server probing is disabled unless AGENT_SECURITY_ADMIN_MODE=1.";
const NPX_ALLOWED_FLAGS = new Set(["-y", "--yes"]);

module.exports = {
  MAX_COMMAND_LENGTH,
  MAX_ARGS,
  MAX_ARG_LENGTH,
  MAX_ENV_KEYS,
  MAX_ENV_VALUE_LENGTH,
  MAX_JSON_INPUT_CHARS,
  MAX_SYSTEM_PROMPT_CHARS,
  MAX_TOOLS,
  MAX_TOOL_LENGTH,
  MAX_PACKAGE_NAME_LENGTH,
  MAX_TEST_PII_LENGTH,
  MAX_SERVERS_PER_CONFIG,
  ACTIVE_SERVER_PROBING_DISABLED_MESSAGE,
  NPX_ALLOWED_FLAGS
};
